# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

#Timezone
timezone:         America/Winnipeg

# Setup
title:            Process & Technology
tagline:          An Open Democracy Manitoba Blog
url:              http://opendemocracymanitoba.github.io

author:
  name:           Kyle Geske
  url:            https://twitter.com/stungeye

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/OpenDemocracyManitoba/OpenDemocracyManitoba.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
